# Generated by Django 6.0.2 on 2026-02-25 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_phone', models.CharField(max_length=11)),
                ('second_phone', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
            ],
        ),
    ]
