# Generated by Django 6.0.2 on 2026-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='login',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='second_phone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
